@isTest
private class TestCaseTriggerMethods 
{
    static testMethod void testProcessConfigurationRequest() 
    {
       /* Account acc = new Account(Name='dummy account');
        insert acc;
        
        Contact con = new Contact(AccountId=acc.Id, Lastname='last', Firstname='first', Email='firstname.lastname@email.com');
        insert con;
        
        List<Case> lstCases = new List<Case>();
        lstCases.add(new Case(AccountId=acc.Id, Subject='test case', Start_Date__c=Date.today(), Req_Type__c='Configuration Request',Type='Training'));
        insert lstCases;
        
        update lstCases;*/
    }
}